version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: kanban-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kanban
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - kanban-network
    command: mongod --auth

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  kanban-network:
    driver: bridge