spring:
   application:
      name: kj-kanban

   data:
      mongodb:
         uri: mongodb://admin:password@localhost:27017/kanban?authSource=admin

   thymeleaf:
         cache: false
         prefix: classpath:/templates/
         suffix: .html

server:
   port: 8080

logging:
   level:
      '[com.kanban]': DEBUG
      '[org.springframework.web]': DEBUG
